"""add ShortUrl table

Revision ID: 8a1f6b111be2
Revises: d8d01d2f649f
Create Date: 2022-10-01 11:15:30.617041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1f6b111be2'
down_revision = 'd8d01d2f649f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short url record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=True),
    sa.Column('short_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_url'),
    sa.UniqueConstraint('short_url')
    )
    op.create_index(op.f('ix_short url record_id'), 'short url record', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short url record_id'), table_name='short url record')
    op.drop_table('short url record')
    # ### end Alembic commands ###
